# Generated by Django 5.0 on 2023-12-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcode', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(max_length=255)),
                ('property_address', models.CharField(max_length=255)),
                ('instructions', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='fubId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messageuser',
            name='fubId',
            field=models.IntegerField(unique=True),
        ),
    ]
