# Generated by Django 5.0 on 2023-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_textcode_alter_messagehistory_fubid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='role',
            field=models.CharField(choices=[('Human', 'Human'), ('AI', 'AI'), ('System', 'System')], max_length=10),
        ),
    ]
