# Generated by Django 5.0 on 2023-12-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_messagehistory_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageHistory',
            new_name='FubMessageHistory',
        ),
        migrations.RenameModel(
            old_name='MessageUser',
            new_name='FUBMessageUser',
        ),
    ]
