# Generated by Django 5.0.1 on 2024-01-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_openaiprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiprompt',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='openaiprompt',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='unique_key_version'),
        ),
    ]
