# Generated by Django 5.0.1 on 2024-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_smsmarkedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmarkedmessage',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
