# Generated by Django 5.0.1 on 2024-02-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fubhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FubWebhook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
