# Generated by Django 5.0.1 on 2024-02-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_fubwebhook_fub_id_alter_fubwebhook_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fubwebhook',
            old_name='fub_id',
            new_name='webhookId',
        ),
    ]
